### ISSUE TITLE
Refactor tuple structs

### ISSUE THREAD

**Issue by adelhult** [adelhult/hypatia#2]
I find tuple struct really hard to read  (`thing.0 . 1`) so it might be a good idea to convert most of them into normal structs.

**Comment by CMDJojo** [comment]
I used them in Trie when a Trie basically is a wrapper around the root node, and I don't think that is too hard to read. `remove(x) = self.0.remove(x)` is a basic delegation, so I think that would work. Does that work for you?

**Comment by CMDJojo** [comment]
Or, from the actual code,
```rs
pub fn purge(&mut self) {
    self.0.purge();
}
```
